#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                script{
                    def equals = "true"
                    equals = sh "diff module.txt module.txt"
                    echo equals
                    if(fileExists("module.txt")) {
                        if(equals == null) {
                            echo 'Same'
                        } else {
                            echo 'Not Same'
                        }
                    } else {
                        echo 'File does not exist'
                    }
                }
            }
        }
    }
}